trigger:
- main

pool:
  name: Default
  demands:
    - agent.name -equals MEHDI  # replace with your agent name

steps:
- script: |
    python -m venv venv
    venv\Scripts\activate
    pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    echo "Running Flask app..."
    start /B venv\Scripts\python.exe app.py
  displayName: 'Run Flask app in background'
