trigger:
- main

pool:
  name: Default
  demands:
    - agent.name -equals MEHDI  # نام Agent شما

steps:
# نصب dependencies
- script: |
    python -m venv venv
    venv\Scripts\activate
    pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

# اجرای Flask در foreground (بدون start /B)
- script: |
    venv\Scripts\python.exe app.py
  displayName: 'Run Flask interactively'
