trigger:
- main

pool:
  name: Default
  demands:
    - agent.name -equals MEHDI

steps:
- script: |
    python -m venv venv
    venv\Scripts\python.exe -m pip install --upgrade pip
    venv\Scripts\python.exe -m pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    echo "Running Flask in background..."
    start "" venv\Scripts\python.exe app.py
  displayName: 'Run Flask in background'


